# Generated by Django 5.2.7 on 2025-11-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ["artist", "id"]},
        ),
        migrations.AddField(
            model_name="song",
            name="album_cover",
            field=models.ImageField(blank=True, null=True, upload_to="album_covers/"),
        ),
        migrations.AddField(
            model_name="song",
            name="release_year",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
