# Generated by Django 5.2.7 on 2025-12-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="photo",
        ),
    ]
