# Generated by Django 5.2.7 on 2025-12-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_remove_artist_bio_remove_artist_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="cover",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="albums"
            ),
        ),
    ]
