# Generated by Django 5.2.7 on 2025-12-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
